### ISSUE TITLE
Read From ID Card With Only NFC Without MRZ

### ISSUE THREAD

**Issue by ErsinDemirbas** [alimertozdemir/EPassportNFCReader#11]
Hi, I am new on Nfc and I wonder that is this possiable to read personel info from an ID Card/Passport with just NFC without MRZ? I have tried this but had got some different things.

**Comment by alimertozdemir** [comment]
Sure Ersin, you can read card without scan MRZ part. We scan MRZ part of id card in order to extract birthday, expire date and document number. We need these three values in order to create Basic Access Control key. So, if you get these three values on UI as a user input or you have already have user identity information on server side than it is okay. You may skip the MRZ read part and create Basic access control directly. The link below shows how to create basic access control key. I hope it helps. 
https://github.com/alimertozdemir/EPassportNFCReader/blob/b7828a21eb637ced07526d84e37df793d5482254/app/src/main/java/com/alimert/passportreader/ui/MainActivity.java#L211

**Comment by ErsinDemirbas** [comment]
No actually I meant to get person's information without need to his birthday, expire date or document number just via Nfc. I think this is not possiable because all examples wich I saw need these 3 input but I had wanted to be sure about this. By the way thanks for your quick commend.

**Comment by alimertozdemir** [comment]
If we talk about reading id card from "chip", no it's not possible. In order to read personal information on chip, you should have bac key. I don't know your usecase, however if you want to get id card details and you don't need to verify chip, then it is possible to scan front side of id card with any OCR and extract data with text recognition. :)

**Comment by ErsinDemirbas** [comment]
Ok I understand it now. I have wanted to read person's all informations directly from the chip with Nfc but I had had to have a bac key 👍 . Ok thaks a lot Ali Mert and I see you know well how to use all of these damn technologies so I wish a perfect career for you :)
